language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t highvelcty/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true highvelcty/docker-react npm run test -- --coverage

